
services:
  server1:
    image: server-image
    container_name: server1
    ports:
      - "9999:9999"
    volumes:
      - ./src/server/files:/app/files
      - ./src/server/config:/app/config
      - ./src/server/db:/app/db
      - ./src/server/logs:/app/logs